[package]
name = "okx-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.13", features = ["json"] }
base64 = "0.13.0"
ring = "0.16.20"
thiserror = "1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = {version = "1.0", features = ["arbitrary_precision"]}
serde_qs = "0.10.1"
rust_decimal = "1.27.0"
anyhow = { version = "1.0.68", features = ["backtrace"] }
log = "0.4.17"

[dev-dependencies]
tokio = { version = "1.18.2", features = ["full", "time", "sync", "tracing"] }
